//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5483
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace TSS.Domain
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReport
    {

        private TDSReportTest testField;

        private TDSReportExaminee examineeField;

        private TDSReportOpportunity opportunityField;

        private TDSReportComment[] commentField;

        private TDSReportToolUsage[] toolUsageField;

        /// <remarks/>
        public TDSReportTest Test
        {
            get { return this.testField; }
            set { this.testField = value; }
        }

        /// <remarks/>
        public TDSReportExaminee Examinee
        {
            get { return this.examineeField; }
            set { this.examineeField = value; }
        }

        /// <remarks/>
        public TDSReportOpportunity Opportunity
        {
            get { return this.opportunityField; }
            set { this.opportunityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comment")]
        public TDSReportComment[] Comment
        {
            get { return this.commentField; }
            set { this.commentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ToolUsage")]
        public TDSReportToolUsage[] ToolUsage
        {
            get { return this.toolUsageField; }
            set { this.toolUsageField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportTest
    {

        private string nameField;

        private string subjectField;

        private string testIdField;

        private uint bankKeyField;

        private bool bankKeyFieldSpecified;

        private string contractField;

        private TDSReportTestMode modeField;

        private string gradeField;

        private uint handScoreProjectField;

        private bool handScoreProjectFieldSpecified;

        private string assessmentTypeField;

        private uint academicYearField;

        private string assessmentVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subject
        {
            get { return this.subjectField; }
            set { this.subjectField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testId
        {
            get { return this.testIdField; }
            set { this.testIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint bankKey
        {
            get { return this.bankKeyField; }
            set { this.bankKeyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bankKeySpecified
        {
            get { return this.bankKeyFieldSpecified; }
            set { this.bankKeyFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contract
        {
            get { return this.contractField; }
            set { this.contractField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TDSReportTestMode mode
        {
            get { return this.modeField; }
            set { this.modeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade
        {
            get { return this.gradeField; }
            set { this.gradeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint handScoreProject
        {
            get { return this.handScoreProjectField; }
            set { this.handScoreProjectField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool handScoreProjectSpecified
        {
            get { return this.handScoreProjectFieldSpecified; }
            set { this.handScoreProjectFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assessmentType
        {
            get { return this.assessmentTypeField; }
            set { this.assessmentTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint academicYear
        {
            get { return this.academicYearField; }
            set { this.academicYearField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assessmentVersion
        {
            get { return this.assessmentVersionField; }
            set { this.assessmentVersionField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum TDSReportTestMode
    {

        /// <remarks/>
        online,

        /// <remarks/>
        paper,

        /// <remarks/>
        scanned,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScoreInfoType
    {

        private object scoreRationaleField;

        private ScoreInfoType[] subScoreListField;

        private string scorePointField;

        private string scoreDimensionField;

        private string scoreStatusField;

        //private bool scoreStatusFieldSpecified;

        private string conditionCodeField;

        /// <remarks/>
        public object ScoreRationale
        {
            get { return this.scoreRationaleField; }
            set { this.scoreRationaleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ScoreInfo", IsNullable = false)]
        public ScoreInfoType[] SubScoreList
        {
            get { return this.subScoreListField; }
            set { this.subScoreListField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scorePoint
        {
            get { return this.scorePointField; }
            set { this.scorePointField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scoreDimension
        {
            get { return this.scoreDimensionField; }
            set { this.scoreDimensionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scoreStatus
        {
            get { return this.scoreStatusField; }
            set { this.scoreStatusField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionCode
        {
            get { return this.conditionCodeField; }
            set { this.conditionCodeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ScoreInfoTypeScoreStatus 
    {

        /// <remarks/>
        Scored,

        /// <remarks/>
        NotScored,

        /// <remarks/>
        WaitingForMachineScore,

        /// <remarks/>
        ScoringError,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportExaminee
    {

        private object[] itemsField;

        private long keyField;

        private bool keyFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExamineeAttribute", typeof (TDSReportExamineeExamineeAttribute))]
        [System.Xml.Serialization.XmlElementAttribute("ExamineeRelationship",
            typeof (TDSReportExamineeExamineeRelationship))]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long key
        {
            get { return this.keyField; }
            set { this.keyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keySpecified
        {
            get { return this.keyFieldSpecified; }
            set { this.keyFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportExamineeExamineeAttribute
    {

        private Context contextField;

        private string nameField;

        private string valueField;

        private System.DateTime contextDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Context context
        {
            get { return this.contextField; }
            set { this.contextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime contextDate
        {
            get { return this.contextDateField; }
            set { this.contextDateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum Context
    {

        /// <remarks/>
        INITIAL,

        /// <remarks/>
        FINAL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportExamineeExamineeRelationship
    {

        private Context contextField;

        private string nameField;

        private ulong entityKeyField;

        private bool entityKeyFieldSpecified;

        private string valueField;

        private System.DateTime contextDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Context context
        {
            get { return this.contextField; }
            set { this.contextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong entityKey
        {
            get { return this.entityKeyField; }
            set { this.entityKeyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityKeySpecified
        {
            get { return this.entityKeyFieldSpecified; }
            set { this.entityKeyFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime contextDate
        {
            get { return this.contextDateField; }
            set { this.contextDateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportOpportunity
    {

        private TDSReportOpportunitySegment[] segmentField;

        private TDSReportOpportunityAccommodation[] accommodationField;

        private TDSReportOpportunityScore[] scoreField;

        private TDSReportOpportunityGenericVariable[] genericVariableField;

        private TDSReportOpportunityItem[] itemField;

        private string serverField;

        private string databaseField;

        private string clientNameField;

        private string keyField;

        private string oppIdField;

        private string startDateField;

        private TDSReportOpportunityStatus statusField;

        private uint opportunityField;

        private System.DateTime statusDateField;

        private string dateCompletedField;

        private uint pauseCountField;

        private uint itemCountField;

        private uint ftCountField;

        private uint abnormalStartsField;

        private uint gracePeriodRestartsField;

        private string taIdField;

        private string taNameField;

        private string sessionIdField;

        private string windowIdField;

        private string windowOpportunityField;

        private string dateForceCompletedField;

        private string qaLevelField;

        private string assessmentParticipantSessionPlatformUserAgentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Segment")]
        public TDSReportOpportunitySegment[] Segment
        {
            get { return this.segmentField; }
            set { this.segmentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Accommodation")]
        public TDSReportOpportunityAccommodation[] Accommodation
        {
            get { return this.accommodationField; }
            set { this.accommodationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Score")]
        public TDSReportOpportunityScore[] Score
        {
            get { return this.scoreField; }
            set { this.scoreField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GenericVariable")]
        public TDSReportOpportunityGenericVariable[] GenericVariable
        {
            get { return this.genericVariableField; }
            set { this.genericVariableField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public TDSReportOpportunityItem[] Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string server
        {
            get { return this.serverField; }
            set { this.serverField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string database
        {
            get { return this.databaseField; }
            set { this.databaseField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clientName
        {
            get { return this.clientNameField; }
            set { this.clientNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key
        {
            get { return this.keyField; }
            set { this.keyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oppId
        {
            get { return this.oppIdField; }
            set { this.oppIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startDate
        {
            get { return this.startDateField; }
            set { this.startDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TDSReportOpportunityStatus status
        {
            get { return this.statusField; }
            set { this.statusField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint opportunity
        {
            get { return this.opportunityField; }
            set { this.opportunityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime statusDate
        {
            get { return this.statusDateField; }
            set { this.statusDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dateCompleted
        {
            get { return this.dateCompletedField; }
            set { this.dateCompletedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint pauseCount
        {
            get { return this.pauseCountField; }
            set { this.pauseCountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint itemCount
        {
            get { return this.itemCountField; }
            set { this.itemCountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint ftCount
        {
            get { return this.ftCountField; }
            set { this.ftCountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint abnormalStarts
        {
            get { return this.abnormalStartsField; }
            set { this.abnormalStartsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint gracePeriodRestarts
        {
            get { return this.gracePeriodRestartsField; }
            set { this.gracePeriodRestartsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taId
        {
            get { return this.taIdField; }
            set { this.taIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taName
        {
            get { return this.taNameField; }
            set { this.taNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sessionId
        {
            get { return this.sessionIdField; }
            set { this.sessionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string windowId
        {
            get { return this.windowIdField; }
            set { this.windowIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string windowOpportunity
        {
            get { return this.windowOpportunityField; }
            set { this.windowOpportunityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dateForceCompleted
        {
            get { return this.dateForceCompletedField; }
            set { this.dateForceCompletedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qaLevel
        {
            get { return this.qaLevelField; }
            set { this.qaLevelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assessmentParticipantSessionPlatformUserAgent
        {
            get { return this.assessmentParticipantSessionPlatformUserAgentField; }
            set { this.assessmentParticipantSessionPlatformUserAgentField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportOpportunitySegment
    {

        private string idField;

        private byte positionField;

        private string formIdField;

        private string formKeyField;

        private string algorithmField;

        private string algorithmVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte position
        {
            get { return this.positionField; }
            set { this.positionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formId
        {
            get { return this.formIdField; }
            set { this.formIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formKey
        {
            get { return this.formKeyField; }
            set { this.formKeyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algorithm
        {
            get { return this.algorithmField; }
            set { this.algorithmField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algorithmVersion
        {
            get { return this.algorithmVersionField; }
            set { this.algorithmVersionField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportOpportunityAccommodation
    {

        private string typeField;

        private string valueField;

        private string codeField;

        private uint segmentField;

        private Context contextField;

        private System.DateTime contextDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint segment
        {
            get { return this.segmentField; }
            set { this.segmentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Context context
        {
            get { return this.contextField; }
            set { this.contextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime contextDate
        {
            get { return this.contextDateField; }
            set { this.contextDateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportOpportunityScore
    {

        private string measureOfField;

        private string measureLabelField;

        private string valueField;

        private string standardErrorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string measureOf
        {
            get { return this.measureOfField; }
            set { this.measureOfField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string measureLabel
        {
            get { return this.measureLabelField; }
            set { this.measureLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string standardError
        {
            get { return this.standardErrorField; }
            set { this.standardErrorField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportOpportunityGenericVariable
    {

        private string contextField;

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string context
        {
            get { return this.contextField; }
            set { this.contextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportOpportunityItem
    {

        private TDSReportOpportunityItemResponse responseField;

        private ScoreInfoType scoreInfoField;

        private uint positionField;

        private string segmentIdField;

        private uint bankKeyField;

        private uint keyField;

        private byte operationalField;

        private byte isSelectedField;

        private string formatField;

        private string scoreField;

        private string scoreStatusField;

        //private bool scoreStatusFieldSpecified;

        private System.DateTime adminDateField;

        private uint numberVisitsField;

        private TDSReportOpportunityItemMimeType mimeTypeField;

        private string clientIdField;

        private string strandField;

        private string contentLevelField;

        private uint pageNumberField;

        private uint pageVisitsField;

        private int pageTimeField;

        private byte droppedField;

        /// <remarks/>
        public TDSReportOpportunityItemResponse Response
        {
            get { return this.responseField; }
            set { this.responseField = value; }
        }

        /// <remarks/>
        public ScoreInfoType ScoreInfo
        {
            get { return this.scoreInfoField; }
            set { this.scoreInfoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint position
        {
            get { return this.positionField; }
            set { this.positionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string segmentId
        {
            get { return this.segmentIdField; }
            set { this.segmentIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint bankKey
        {
            get { return this.bankKeyField; }
            set { this.bankKeyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint key
        {
            get { return this.keyField; }
            set { this.keyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte operational
        {
            get { return this.operationalField; }
            set { this.operationalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isSelected
        {
            get { return this.isSelectedField; }
            set { this.isSelectedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format
        {
            get { return this.formatField; }
            set { this.formatField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string score
        {
            get { return this.scoreField; }
            set { this.scoreField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scoreStatus
        {
            get
            {
                return this.scoreStatusField;
            }
            set { this.scoreStatusField = value.ToString(); }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime adminDate
        {
            get { return this.adminDateField; }
            set { this.adminDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint numberVisits
        {
            get { return this.numberVisitsField; }
            set { this.numberVisitsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TDSReportOpportunityItemMimeType mimeType
        {
            get { return this.mimeTypeField; }
            set { this.mimeTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clientId
        {
            get { return this.clientIdField; }
            set { this.clientIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strand
        {
            get { return this.strandField; }
            set { this.strandField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentLevel
        {
            get { return this.contentLevelField; }
            set { this.contentLevelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint pageNumber
        {
            get { return this.pageNumberField; }
            set { this.pageNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint pageVisits
        {
            get { return this.pageVisitsField; }
            set { this.pageVisitsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageTime
        {
            get { return this.pageTimeField; }
            set { this.pageTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte dropped
        {
            get { return this.droppedField; }
            set { this.droppedField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportOpportunityItemResponse
    {

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        private TDSReportOpportunityItemResponseType typeField;

        private bool typeFieldSpecified;

        private string[] textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date
        {
            get { return this.dateField; }
            set { this.dateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get { return this.dateFieldSpecified; }
            set { this.dateFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TDSReportOpportunityItemResponseType type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get { return this.typeFieldSpecified; }
            set { this.typeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get { return this.textField; }
            set { this.textField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum TDSReportOpportunityItemResponseType
    {

        /// <remarks/>
        value,

        /// <remarks/>
        reference,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")] Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum TDSReportOpportunityItemScoreStatus
    {

        /// <remarks/>
        NOTSCORED,

        /// <remarks/>
        SCORED,

        /// <remarks/>
        WAITINGFORMACHINESCORE,

        /// <remarks/>
        SCORINGERROR,

        /// <remarks/>
        APPEALED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum TDSReportOpportunityItemMimeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("text/plain")] textplain,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("text/xml")] textxml,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("text/html")] texthtml,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("audio/ogg")] audioogg,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum TDSReportOpportunityStatus
    {

        /// <remarks/>
        appeal,

        /// <remarks/>
        completed,

        /// <remarks/>
        expired,

        /// <remarks/>
        handscoring,

        /// <remarks/>
        invalidated,

        /// <remarks/>
        paused,

        /// <remarks/>
        reported,

        /// <remarks/>
        reset,

        /// <remarks/>
        scored,

        /// <remarks/>
        submitted,

        /// <remarks/>
        pending,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportComment
    {

        private string contextField;

        private string itemPositionField;

        private System.DateTime dateField;

        private string[] textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string context
        {
            get { return this.contextField; }
            set { this.contextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string itemPosition
        {
            get { return this.itemPositionField; }
            set { this.itemPositionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date
        {
            get { return this.dateField; }
            set { this.dateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get { return this.textField; }
            set { this.textField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportToolUsage
    {

        private TDSReportToolUsageToolPage[] toolPageField;

        private string typeField;

        private string codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ToolPage")]
        public TDSReportToolUsageToolPage[] ToolPage
        {
            get { return this.toolPageField; }
            set { this.toolPageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TDSReportToolUsageToolPage
    {

        private uint pageField;

        private string groupIdField;

        private uint countField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint page
        {
            get { return this.pageField; }
            set { this.pageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string groupId
        {
            get { return this.groupIdField; }
            set { this.groupIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint count
        {
            get { return this.countField; }
            set { this.countField = value; }
        }
    }
}